(function(g){var window=this;var LBa=function(a,b){return g.Wb(a,b)},z6=function(a){g.Im(a,"zx",g.xb());
return a},A6=function(a,b,c){g.za(c)||(c=[String(c)]);
g.Lm(a.o,b,c)},MBa=function(a,b){var c=[];
g.wk(b,function(a){try{var b=g.gD.prototype.A.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.v(b)?g.fD(b)&&c.push(a):c.push(a)},a);
return c},NBa=function(a,b){var c=MBa(a,b);
(0,g.C)(c,function(a){g.gD.prototype.remove.call(this,a)},a)},OBa=function(a){if(a.Ed){if(a.Ed.locationOverrideToken)return{locationOverrideToken:a.Ed.locationOverrideToken};
if(null!=a.Ed.latitudeE7&&null!=a.Ed.longitudeE7)return{latitudeE7:a.Ed.latitudeE7,longitudeE7:a.Ed.longitudeE7}}return null},PBa=function(a,b,c,d){var e=new g.zm(null,void 0);
a&&g.Am(e,a);b&&g.Bm(e,b);c&&g.Cm(e,c);d&&g.Dm(e,d);return e},QBa=function(a){g.WF[a]&&(a=g.WF[a],(0,g.C)(a,function(a){g.UF[a]&&delete g.UF[a]}),a.length=0)},RBa=function(a){var b=g.TF();
if(b)if(b.clear(a),a)QBa(a);else for(var c in g.WF)QBa(c)},B6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.B=!1;this.capabilities=new window.Set;this.experiments=new window.Set;this.theme="u";new g.tm;this.o=this.A="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",SBa(this,a.capabilities||""),TBa(this,a.experiments||""),this.A=a.remoteControllerUrl||"",
this.o=a.localChannelEncryptionKey||"")},SBa=function(a,b){a.capabilities.clear();
(0,g.Ld)(b.split(","),g.Fa(LBa,UBa)).forEach(function(b){a.capabilities.add(b)})},TBa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},C6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},D6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},VBa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},WBa=function(a){return new C6(a)},XBa=function(a){return g.za(a)?(0,g.I)(a,WBa):[]},E6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},F6=function(a){return g.za(a)?"["+(0,g.I)(a,E6).join(",")+"]":"null"},G6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},YBa=function(a){return(0,g.I)(a,function(a){return{key:a.id,
name:a.name}})},H6=function(a,b){return g.Ka(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},I6=function(a,b){return g.Ka(a,function(a){return D6(a,b)})},ZBa=function(){var a=(0,g.SG)();
a&&NBa(a,a.o.Zd(!0))},J6=function(){var a=g.VG("yt-remote-connected-devices")||[];
g.gb(a);return a},$Ba=function(a){if(g.Pa(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.I)(a,function(a,b){return 0==b?a:a.substring(c.length)})},aCa=function(a){g.UG("yt-remote-connected-devices",a,86400)},L6=function(){if(K6)return K6;
var a=g.VG("yt-remote-device-id");a||(a=G6(),g.UG("yt-remote-device-id",a,31536E3));for(var b=J6(),c=1,d=a;g.Oa(b,d);)c++,d=a+"#"+c;return K6=d},M6=function(){var a=J6(),b=L6();
g.Oa(a,b);g.XG()&&g.kb(a,b);a=$Ba(a);if(g.Pa(a))try{g.EG("remote_sid")}catch(c){}else try{g.DG("remote_sid",a.join(","),-1)}catch(c){}},bCa=function(){return g.VG("yt-remote-session-browser-channel")},cCa=function(){return g.VG("yt-remote-local-screens")||[]},dCa=function(){g.UG("yt-remote-lounge-token-expiration",!0,86400)},eCa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.I)(cCa(),function(a){return a.loungeToken}),c=(0,g.I)(a,function(a){return a.loungeToken});
(0,g.hm)(c,function(a){return!g.Oa(b,a)})&&dCa();
g.UG("yt-remote-local-screens",a,31536E3)},fCa=function(a,b){g.UG("yt-remote-session-browser-channel",a);
g.UG("yt-remote-session-screen-id",b);var c=J6(),d=L6();g.Oa(c,d)||c.push(d);aCa(c);M6()},N6=function(a){a||(g.WG("yt-remote-session-screen-id"),g.WG("yt-remote-session-video-id"));
M6();a=J6();g.Ta(a,L6());aCa(a)},gCa=function(){if(!O6){var a=g.rD();
a&&(O6=new g.aD(a))}return O6?!!O6.get("yt-remote-use-staging-server"):!1},hCa=function(){var a=window.document.createElement("a");
g.$c(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Bb(a)},iCa=function(a,b){var c=g.Ed("SCRIPT");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
g.ad(c,g.ce("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},jCa=function(){var a=hCa(),b=window.document.getElementById(a),c=b&&g.eF(b,"loaded");
c||b&&!c||(b=iCa(a,function(){g.eF(b,"loaded")||(g.dF(b,"loaded","true"),g.$F(a),g.$D(g.Fa(RBa,a),0))}))},P6=function(a){return!!window.document.currentScript&&(-1!=window.document.currentScript.src.indexOf("?"+a)||-1!=window.document.currentScript.src.indexOf("&"+a))},kCa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},Q6=function(a){a.length?lCa(a.shift(),function(){Q6(a)}):R6()},mCa=function(a){return"chrome-extension://"+a+S6},lCa=function(a,
b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},T6=function(a){return 0<=window.navigator.userAgent.indexOf(a)},R6=function(){var a=kCa();
a&&a(!1,"No cast extension found")},U6=function(){if(nCa){var a=2,b=kCa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;lCa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",R6,c)}},oCa=function(){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
a&&(U6(),a({command:"cast.sender.init"}))},pCa=function(){U6();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);Q6(["//www.gstatic.com/eureka/clank/"+(a?(0,window.parseInt)(a[1],10):0)+S6,"//www.gstatic.com/eureka/clank"+S6])},V6=function(a,b,c){g.M.call(this);
this.F=null!=c?(0,g.A)(a,c):a;this.wd=b;this.D=(0,g.A)(this.nK,this);this.o=!1;this.A=0;this.B=this.Fa=null;this.C=[]},W6=function(){},X6=function(a,b,c,d){this.o=a;
this.B=b;this.G=c;this.F=d||1;this.C=45E3;this.Y=new g.Pm(this);this.A=new g.wg;this.A.setInterval(250)},rCa=function(a,b,c){a.Uj=1;
a.th=z6(b.clone());a.bj=c;a.D=!0;qCa(a,null)},Y6=function(a,b,c,d,e){a.Uj=1;
a.th=z6(b.clone());a.bj=null;a.D=c;e&&(a.CE=!1);qCa(a,d)},qCa=function(a,b){a.Lk=(0,g.G)();
Z6(a);a.Qh=a.th.clone();A6(a.Qh,"t",a.F);a.fn=0;a.Tc=a.o.ls(a.o.Tm()?b:null);0<a.Us&&(a.bq=new g.$k((0,g.A)(a.UF,a,a.Tc),a.Us));a.Y.W(a.Tc,"readystatechange",a.KV);var c=a.zi?g.dc(a.zi):{};a.bj?(a.Rq="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Tc.send(a.Qh,a.Rq,a.bj,c)):(a.Rq="GET",a.CE&&!g.Ad&&(c.Connection="close"),a.Tc.send(a.Qh,a.Rq,null,c));a.o.Df(1)},uCa=function(a,b,c){for(var d=!0;!a.hi&&a.fn<c.length;){var e=sCa(a,c);
if(e==$6){4==b&&(a.uh=4,a7(15),d=!1);break}else if(e==tCa){a.uh=4;a7(16);d=!1;break}else b7(a,e)}4==b&&0==c.length&&(a.uh=1,a7(17),d=!1);a.Jf=a.Jf&&d;d||(c7(a),d7(a))},sCa=function(a,b){var c=a.fn,d=b.indexOf("\n",c);
if(-1==d)return $6;c=Number(b.substring(c,d));if((0,window.isNaN)(c))return tCa;d+=1;if(d+c>b.length)return $6;var e=b.substr(d,c);a.fn=d+c;return e},wCa=function(a,b){a.Lk=(0,g.G)();
Z6(a);var c=b?window.location.hostname:"";a.Qh=a.th.clone();g.Im(a.Qh,"DOMAIN",c);g.Im(a.Qh,"t",a.F);try{a.Kf=new window.ActiveXObject("htmlfile")}catch(n){c7(a);a.uh=7;a7(22);d7(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in e7)k=e7[l];else if(l in vCa)k=e7[l]=vCa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=
m.toString(16).toUpperCase()}k=e7[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}d+="</body></html>";c=g.bd(g.wc("b/12014412"),d);a.Kf.open();a.Kf.write(g.Uc(c));a.Kf.close();a.Kf.parentWindow.m=(0,g.A)(a.SU,a);a.Kf.parentWindow.d=(0,g.A)(a.LD,a,!0);a.Kf.parentWindow.rpcClose=(0,g.A)(a.LD,a,!1);c=a.Kf.createElement("DIV");a.Kf.parentWindow.document.body.appendChild(c);d=g.Kc(a.Qh.toString());d=g.rb(g.Hc(d));d=g.bd(g.wc("b/12014412"),'<iframe src="'+d+'"></iframe>');c.innerHTML=g.Uc(d);
a.o.Df(1)},Z6=function(a){a.Cw=(0,g.G)()+a.C;
xCa(a,a.C)},xCa=function(a,b){if(null!=a.dl)throw Error("WatchDog timer not null");
a.dl=f7((0,g.A)(a.iV,a),b)},g7=function(a){a.dl&&(g.x.clearTimeout(a.dl),a.dl=null)},d7=function(a){a.o.Tz()||a.hi||a.o.Np(a)},c7=function(a){g7(a);
g.cf(a.bq);a.bq=null;a.A.stop();g.Vm(a.Y);if(a.Tc){var b=a.Tc;a.Tc=null;b.abort();b.dispose()}a.Kf&&(a.Kf=null)},b7=function(a,b){try{a.o.DD(a,b),a.o.Df(4)}catch(c){}},zCa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;yCa(a,b,function(e){e?c(!0):g.x.setTimeout(function(){zCa(a,b,c,d,f)},f)})}},yCa=function(a,b,c){var d=new window.Image;
d.onload=function(){try{h7(d),c(!0)}catch(e){}};
d.onerror=function(){try{h7(d),c(!1)}catch(e){}};
d.onabort=function(){try{h7(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{h7(d),c(!1)}catch(e){}};
g.x.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},h7=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},ACa=function(a){this.o=a;
this.A=new W6},BCa=function(a){var b=i7(a.o,a.rl,"/mail/images/cleardot.gif");
z6(b);zCa(b.toString(),5E3,(0,g.A)(a.zJ,a),3,2E3);a.Df(1)},k7=function(a){var b=a.o.J;
if(null!=b)a7(5),b?(a7(11),j7(a.o,a,!1)):(a7(12),j7(a.o,a,!0));else if(a.Ae=new X6(a,void 0,void 0,void 0),a.Ae.zi=a.Ss,b=a.o,b=i7(b,b.Tm()?a.Rl:null,a.Ts),a7(5),!g.yd||g.sc(10))A6(b,"TYPE","xmlhttp"),Y6(a.Ae,b,!1,a.Rl,!1);else{A6(b,"TYPE","html");var c=a.Ae;a=!!a.Rl;c.Uj=3;c.th=z6(b.clone());wCa(c,a)}},l7=function(a,b,c){this.o=1;
this.A=[];this.C=[];this.D=new W6;this.H=a||null;this.J=null!=b?b:null;this.F=c||!1},CCa=function(a,b){this.o=a;
this.map=b;this.context=null},DCa=function(a){g.ef.call(this,"statevent",a)},ECa=function(a,b){g.ef.call(this,"timingevent",a);
this.size=b},FCa=function(a){g.ef.call(this,"serverreachability",a)},ICa=function(a){GCa(a);
if(3==a.o){var b=a.Dm++,c=a.to.clone();g.Im(c,"SID",a.B);g.Im(c,"RID",b);g.Im(c,"TYPE","terminate");m7(a,c);b=new X6(a,a.B,b,void 0);b.Uj=2;b.th=z6(c.clone());(new window.Image).src=b.th;b.Lk=(0,g.G)();Z6(b)}HCa(a)},JCa=function(a){a.UJ(1,0);
a.to=i7(a,null,a.Rs);n7(a)},GCa=function(a){a.jh&&(a.jh.abort(),a.jh=null);
a.xc&&(a.xc.cancel(),a.xc=null);a.zg&&(g.x.clearTimeout(a.zg),a.zg=null);o7(a);a.fe&&(a.fe.cancel(),a.fe=null);a.lh&&(g.x.clearTimeout(a.lh),a.lh=null)},KCa=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.A.push(new CCa(a.FQ++,b));2!=a.o&&3!=a.o||n7(a)},n7=function(a){a.fe||a.lh||(a.lh=f7((0,g.A)(a.JD,a),0),a.Jj=0)},MCa=function(a,b){if(1==a.o){if(!b){a.Dm=Math.floor(1E5*Math.random());
var c=a.Dm++,d=new X6(a,"",c,void 0);d.zi=null;var e=p7(a),f=a.to.clone();g.Im(f,"RID",c);g.Im(f,"CVER","1");m7(a,f);rCa(d,f,e);a.fe=d;a.o=2}}else 3==a.o&&(b?LCa(a,b):0==a.A.length||a.fe||LCa(a))},LCa=function(a,b){if(b)if(6<a.ji){a.A=a.C.concat(a.A);
a.C.length=0;var c=a.Dm-1;var d=p7(a)}else c=b.G,d=b.bj;else c=a.Dm++,d=p7(a);var e=a.to.clone();g.Im(e,"SID",a.B);g.Im(e,"RID",c);g.Im(e,"AID",a.ik);m7(a,e);c=new X6(a,a.B,c,a.Jj+1);c.zi=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.fe=c;rCa(c,e,d)},m7=function(a,b){if(a.ud){var c=a.ud.Bz();
c&&g.Jb(c,function(a,c){g.Im(b,c,a)})}},p7=function(a){var b=Math.min(a.A.length,1E3),c=["count="+b];
if(6<a.ji&&0<b){var d=a.A[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.A[e].o,k=a.A[e].map;f=6>=a.ji?e:f-d;try{g.Jb(k,function(a,b){c.push("req"+f+"_"+b+"="+(0,window.encodeURIComponent)(a))})}catch(l){c.push("req"+f+"_type="+(0,window.encodeURIComponent)("_badmap"))}}a.C=a.C.concat(a.A.splice(0,b));
return c.join("&")},NCa=function(a){a.xc||a.zg||(a.G=1,a.zg=f7((0,g.A)(a.ID,a),0),a.wj=0)},q7=function(a){if(a.xc||a.zg||3<=a.wj)return!1;
a.G++;a.zg=f7((0,g.A)(a.ID,a),OCa(a,a.wj));a.wj++;return!0},j7=function(a,b,c){a.Qq=c;
a.Zf=b.Kg;a.F||JCa(a)},o7=function(a){null!=a.mi&&(g.x.clearTimeout(a.mi),a.mi=null)},OCa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},r7=function(a,b){if(2==b||9==b){var c=null;
a.ud&&(c=null);var d=(0,g.A)(a.EW,a);c||(c=new g.zm("//www.google.com/images/cleardot.gif"),z6(c));yCa(c.toString(),1E4,d)}else a7(2);PCa(a,b)},PCa=function(a,b){a.o=0;
a.ud&&a.ud.uy(b);HCa(a);GCa(a)},HCa=function(a){a.o=0;
a.Zf=-1;if(a.ud)if(0==a.C.length&&0==a.A.length)a.ud.Tr();else{g.Xa(a.C);var b=g.Xa(a.A);a.C.length=0;a.A.length=0;a.ud.Tr(b)}},i7=function(a,b,c){var d=g.Jm(c);
if(""!=d.A)b&&g.Bm(d,b+"."+d.A),g.Cm(d,d.D);else{var e=window.location;d=PBa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Dl&&g.Jb(a.Dl,function(a,b){g.Im(d,b,a)});
g.Im(d,"VER",a.ji);m7(a,d);return d},f7=function(a,b){if(!g.Ba(a))throw Error("Fn must not be null and must be a function");
return g.x.setTimeout(function(){a()},b)},a7=function(a){s7.dispatchEvent(new DCa(s7,a))},QCa=function(){},RCa=function(a,b){this.action=a;
this.params=b||{}},t7=function(a,b){g.M.call(this);
this.o=new g.bu(this.JU,0,this);g.N(this,this.o);this.wd=5E3;this.A=0;if(g.Ba(a))b&&(a=(0,g.A)(a,b));else if(a&&g.Ba(a.handleEvent))a=(0,g.A)(a.handleEvent,a);else throw Error("Invalid listener argument");this.B=a},u7=function(a,b,c){this.L=a;
this.F=b;this.B=new g.$C;this.A=new t7(this.oX,this);this.o=this.bb=null;this.K=!1;this.D=null;this.J="";this.H=this.C=0;this.G=[];this.M=c||!1},SCa=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.Qq,sessionId:a.o.B,arrayId:a.o.ik}},TCa=function(a,b){a.H=b||0;
a.A.stop();a.o&&(3==a.o.o&&MCa(a.o),ICa(a.o));a.H=0},v7=function(a){return!!a.o&&3==a.o.o},UCa=function(a,b){(a.F.loungeIdToken=b)||a.A.stop()},w7=function(a){this.port=this.domain="";
this.o="/api/lounge";this.A=!0;a=a||window.document.location.href;var b=g.Mg(a)||"";b&&(this.port=":"+b);this.domain=g.Lg(a)||"";a=g.Hb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Ab(a,"10.0")&&(this.A=!1))},x7=function(a,b){var c=a.o;
if(g.v(void 0)?0:a.A)c="https://"+a.domain+a.port+a.o;return g.Vg(c+b,{})},y7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Fa(a.C,d,!0),onError:g.Fa(a.B,e),Bd:g.Fa(a.D,e)};c&&(a.Qb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.qE(b,a)},YCa=function(){var a=VCa;
WCa();z7.push(a);XCa(z7)},A7=function(a,b){WCa();
var c=z7,d=ZCa(a,String(b));g.Pa(c)?$Ca(d):(XCa(c),(0,g.C)(c,function(a){a(d)}))},WCa=function(){z7||(z7=g.y("yt.mdx.remote.debug.handlers_")||[],g.ua("yt.mdx.remote.debug.handlers_",z7,void 0))},$Ca=function(a){var b=(B7+1)%50;
B7=b;C7[b]=a;D7||(D7=49==b)},XCa=function(a){var b=C7;
if(b[0]){var c=B7,d=D7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.C)(a,function(a){a(e)})}while(d!=c);
C7=Array(50);B7=-1;D7=!1}},ZCa=function(a,b){var c=((0,g.G)()-aDa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},E7=function(a){g.LF.call(this);
this.G=a;this.o=[]},bDa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.o.push(b);return!0},cDa=function(a,b){var c=a.o.length!=b.length;
a.o=(0,g.Ld)(a.o,function(a){return!!H6(b,a)});
for(var d=0,e=b.length;d<e;d++)c=bDa(a,b[d])||c;return c},dDa=function(a,b){var c=a.o.length;
a.o=(0,g.Ld)(a.o,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.o.length<c},F7=function(a,b,c,d){g.LF.call(this);
this.F=a;this.D=b;this.B=c;this.C=d;this.A=0;this.o=null;this.Fa=window.NaN},H7=function(a){E7.call(this,"LocalScreenService");
this.B=a;this.A=window.NaN;G7(this);this.info("Initializing with "+F6(this.o))},eDa=function(a){if(a.o.length){var b=(0,g.I)(a.o,function(a){return a.id}),c=x7(a.B,"/pairing/get_lounge_token_batch");
y7(a.B,c,{screen_ids:b.join(",")},(0,g.A)(a.AK,a),(0,g.A)(a.zK,a))}},G7=function(a){var b=XBa(cCa());
b=(0,g.Ld)(b,function(a){return!a.uuid});
return cDa(a,b)},I7=function(a,b){eCa((0,g.I)(a.o,VBa));
b&&dCa()},K7=function(a,b){g.LF.call(this);
this.F=b;var c=g.VG("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.F(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Oa(c,l)}this.o=d;this.D=a;this.B=this.C=window.NaN;this.A=null;J7("Initialized with "+g.Dg(this.o))},fDa=function(a,b,c){var d=x7(a.D,"/pairing/get_screen_availability");
y7(a.D,d,{lounge_token:b.token},(0,g.A)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.A)(function(){c(!1)},a))},L7=function(a,b){a:if(g.Ob(b)!=g.Ob(a.o))var c=!1;
else{c=g.Rb(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(J7("Updated online screens: "+g.Dg(a.o)),a.o=b,a.V("screenChange"));gDa(a)},M7=function(a){(0,window.isNaN)(a.B)||g.bE(a.B);
a.B=g.$D((0,g.A)(a.Pv,a),0<a.C&&a.C<(0,g.G)()?2E4:1E4)},J7=function(a){A7("OnlineScreenService",a)},hDa=function(a){var b={};
(0,g.C)(a.F(),function(a){a.token?b[a.token]=a.id:this.jc("Requesting availability of screen w/o lounge token.")});
return b},gDa=function(a){a=g.Rb(g.Lb(a.o,function(a){return a}));
g.gb(a);a.length?g.UG("yt-remote-online-screen-ids",a.join(","),60):g.WG("yt-remote-online-screen-ids")},N7=function(a){E7.call(this,"ScreenService");
this.F=a;this.A=this.B=null;this.C=[];this.D={};iDa(this)},kDa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.D[b]);var k=a.se();if(k=(c?I6(k,c):null)||I6(k,b)){k.uuid=b;var l=O7(a,k);fDa(a.A,l,function(a){e(a?l:null)})}else c?jDa(a,c,(0,g.A)(function(a){var f=O7(this,new C6({name:d,
screenId:c,loungeToken:a,dialId:b||""}));fDa(this.A,f,function(a){e(a?f:null)})},a),f):e(null)},lDa=function(a,b){for(var c=0,d=a.o.length;c<d;++c)if(a.o[c].name==b)return a.o[c];
return null},jDa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Qb:{screen_ids:b},method:"POST",context:a,onSuccess:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.qE(x7(a.F,"/pairing/get_lounge_token_batch"),e)},mDa=function(a){a.o=a.B.se();
var b=a.D,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.o.length;b<d;++b){var e=a.o[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+F6(a.o))},iDa=function(a){P7(a);
a.B=new H7(a.F);a.B.subscribe("screenChange",(0,g.A)(a.PK,a));mDa(a);a.C=XBa(g.VG("yt-remote-automatic-screen-cache")||[]);P7(a);a.info("Initializing automatic screens: "+F6(a.C));a.A=new K7(a.F,(0,g.A)(a.se,a,!0));a.A.subscribe("screenChange",(0,g.A)(function(){this.V("onlineScreenChange")},a))},O7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=I6(a.C,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.C.push(b),g.UG("yt-remote-automatic-screen-cache",(0,g.I)(a.C,VBa)));P7(a);a.D[b.uuid]=b.id;g.UG("yt-remote-device-id-map",a.D,31536E3);return b},P7=function(a){a.D=g.VG("yt-remote-device-id-map")||{}},Q7=function(a,b,c){g.LF.call(this);
this.M=c;this.J=a;this.A=b;this.B=null},R7=function(a,b){A7(a.M,b)},S7=function(a,b){Q7.call(this,a,b,"CastSession");
this.o=null;this.C=0;this.F=(0,g.A)(this.uX,this);this.D=(0,g.A)(this.uV,this);this.C=g.$D((0,g.A)(function(){nDa(this,null)},this),12E4)},oDa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Dg(void 0));
var b={type:"getMdxSessionStatus"};a.o?a.o.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.z,(0,g.A)(function(){R7(this,"Failed to send message: getMdxSessionStatus.")},a)):R7(a,"Sending yt message without session: "+g.Dg(b))},nDa=function(a,b){g.bE(a.C);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.B||a.B.id!=b){var c=(0,g.A)(a.Op,a),d=(0,g.A)(a.ye,a);a.Lz(b,c,d,5)}}else a.ye(Error("Waiting for session status timed out."))},T7=function(a,b,c){Q7.call(this,a,b,"DialSession");
this.C=this.H=null;this.K="";this.O=c;this.D=null;this.G=g.z;this.F=window.NaN;this.L=(0,g.A)(this.xX,this);this.o=g.z},pDa=function(a){a.o=a.J.bG(a.K,a.A.label,a.A.friendlyName,(0,g.A)(function(a){this.o=g.z;
this.Op(a)},a),(0,g.A)(function(a){this.o=g.z;
this.ye(a)},a))},qDa=function(a){var b={};
b.pairingCode=a.K;b.theme=a.O;if(a.D){var c=a.D.currentTime||0;b.v=a.D.videoId;b.t=c}gCa()&&(b.env_useStageMdx=1);return g.Tg(b)},U7=function(a,b){Q7.call(this,a,b,"ManualSession");
this.o=g.$D((0,g.A)(this.kk,this,null),150)},V7=function(a,b,c,d){g.LF.call(this);
this.A=a;this.G=b||"233637DE";this.F=c||"cl";this.H=d||!1;this.o=null;this.D=!1;this.B=[];this.C=(0,g.A)(this.UT,this)},rDa=function(a,b){return b?g.Ka(a.B,function(a){return D6(b,a.label)},a):null},W7=function(a){A7("Controller",a)},VCa=function(a){window.chrome&&window.chrome.cast&&window.chrome.cast.logMessage&&window.chrome.cast.logMessage(a)},X7=function(a){return a.D||!!a.B.length||!!a.o},Y7=function(a,b,c){b!=a.o&&(g.cf(a.o),(a.o=b)?(c?a.V("yt-remote-cast2-receiver-resumed",b.A):a.V("yt-remote-cast2-receiver-selected",
b.A),b.subscribe("sessionScreen",(0,g.A)(a.GD,a,b)),b.B?a.V("yt-remote-cast2-session-change",b.B):c&&a.o.kk(null)):a.V("yt-remote-cast2-session-change",null))},sDa=function(a){var b=a.A.aG(),c=a.o&&a.o.A;
a=(0,g.I)(b,function(a){c&&D6(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=rDa(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new window.chrome.cast.Receiver(b,a.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=window.chrome.cast.ReceiverType.CUSTOM&&(c=new window.chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=window.chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},yDa=function(a,b,c,d,e,f,k){tDa()?uDa(b,e,f,k)&&($7(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?vDa(a,c):(window.__onGCastApiAvailable=function(b,d){b?vDa(a,c):(a8("Failed to load cast API: "+d),b8(!1),$7(!1),g.WG("yt-remote-cast-available"),g.WG("yt-remote-cast-receiver"),wDa(),
c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):jCa():T6("CriOS")?oCa():T6("Android")&&T6("Chrome/")&&window.navigator.presentation?pCa():window.chrome&&window.navigator.presentation&&!T6("Edge")?(U6(),Q6(xDa.map(mCa))):R6())):Z7("Cannot initialize because not running Chrome")},wDa=function(){Z7("dispose");
var a=c8();a&&a.dispose();g.ua("yt.mdx.remote.cloudview.instance_",null,void 0);zDa(!1);g.YF(d8);d8.length=0},e8=function(){return!!g.VG("yt-remote-cast-installed")},ADa=function(){var a=g.VG("yt-remote-cast-receiver");
return a?a.friendlyName:null},BDa=function(){Z7("clearCurrentReceiver");
g.WG("yt-remote-cast-receiver")},CDa=function(){return e8()?c8()?c8().getCastSession():(a8("getCastSelector: Cast is not initialized."),null):(a8("getCastSelector: Cast API is not installed!"),null)},g8=function(){e8()?c8()?f8()?(Z7("Requesting cast selector."),c8().requestSession()):(Z7("Wait for cast API to be ready to request the session."),d8.push(g.XF("yt-remote-cast2-api-ready",g8))):a8("requestCastSelector: Cast is not initialized."):a8("requestCastSelector: Cast API is not installed!")},h8=
function(a,b){f8()?c8().setConnectedScreenStatus(a,b):a8("setConnectedScreenStatus called before ready.")},tDa=function(){var a=0<=g.Hb.search(/ (CrMo|Chrome|CriOS)\//);
return g.HI||a},DDa=function(a,b){c8().init(a,b)},uDa=function(a,b,c,d){var e=!1;
c8()||(a=new V7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.UG("yt-remote-cast-available",a);g.aG("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){Z7("onReceiverSelected: "+a.friendlyName);
g.UG("yt-remote-cast-receiver",a);g.aG("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){Z7("onReceiverResumed: "+a.friendlyName);
g.UG("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){Z7("onSessionChange: "+E6(a));
a||g.WG("yt-remote-cast-receiver");g.aG("yt-remote-cast2-session-change",a)}),g.ua("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
Z7("cloudview.createSingleton_: "+e);return e},c8=function(){return g.y("yt.mdx.remote.cloudview.instance_")},vDa=function(a,b){b8(!0);
$7(!1);DDa(a,function(a){a?(zDa(!0),g.$F("yt-remote-cast2-api-ready")):(a8("Failed to initialize cast API."),b8(!1),g.WG("yt-remote-cast-available"),g.WG("yt-remote-cast-receiver"),wDa());b(a)})},Z7=function(a){A7("cloudview",a)},a8=function(a){A7("cloudview",a)},b8=function(a){Z7("setCastInstalled_ "+a);
g.UG("yt-remote-cast-installed",a)},f8=function(){return!!g.y("yt.mdx.remote.cloudview.apiReady_")},zDa=function(a){Z7("setApiReady_ "+a);
g.ua("yt.mdx.remote.cloudview.apiReady_",a,void 0)},$7=function(a){g.ua("yt.mdx.remote.cloudview.initializing_",a,void 0)},i8=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.o=-1;this.muted=!1;this.audioTrackId=null;this.G=this.H=0;this.A=null;this.hasNext=this.dg=!1;this.K=this.J=this.B=this.D=0;this.C=window.NaN;this.F=!1;this.reset(a)},j8=function(a){a.audioTrackId=null;
a.A=null;a.o=-1;a.dg=!1;a.hasNext=!1;a.H=0;a.G=(0,g.G)();a.D=0;a.B=0;a.J=0;a.K=0;a.C=window.NaN;a.F=!1},k8=function(a){return a.rb()?((0,g.G)()-a.G)/1E3:0},l8=function(a,b){a.H=b;
a.G=(0,g.G)()},m8=function(a){switch(a.o){case 1:case 1081:return((0,g.G)()-a.G)/1E3+a.H;
case -1E3:return 0}return a.H},n8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&j8(a)},o8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.o;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.ec(a.A);b.hasPrevious=a.dg;b.hasNext=a.hasNext;b.playerTime=a.H;b.playerTimeAt=a.G;b.seekableStart=a.D;b.seekableEnd=a.B;b.duration=a.J;b.loadedTime=a.K;b.liveIngestionTime=a.C;return b},q8=function(a,b){g.LF.call(this);
this.o=0;this.C=a;this.F=[];this.D=new g.qC;this.B=this.A=null;this.J=(0,g.A)(this.pR,this);this.G=(0,g.A)(this.Gm,this);this.H=(0,g.A)(this.oR,this);this.K=(0,g.A)(this.CR,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Jw,this),EDa(this))):c=3;0!=c&&(b?this.Jw(c):g.$D((0,g.A)(function(){this.Jw(c)},this),0));
var d=CDa();d&&p8(this,d);this.subscribe("yt-remote-cast2-session-change",this.K)},r8=function(a){return new i8(a.C.getPlayerContextData())},EDa=function(a){(0,g.C)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.F.push(this.C.subscribe(a,g.Fa(this.PT,a),this))},a)},FDa=function(a){(0,g.C)(a.F,function(a){this.C.unsubscribeByKey(a)},a);
a.F.length=0},s8=function(a,b){50>a.D.Gc()&&g.sC(a.D,b)},u8=function(a,b,c){var d=r8(a);
l8(d,c);-1E3!=d.o&&(d.o=b);t8(a,d)},v8=function(a,b,c){a.C.sendMessage(b,c)},t8=function(a,b){FDa(a);
a.C.setPlayerContextData(o8(b));EDa(a)},p8=function(a,b){a.B&&(a.B.removeUpdateListener(a.J),a.B.removeMediaListener(a.G),a.Gm(null));
a.B=b;a.B&&(A7("CP","Setting cast session: "+a.B.sessionId),a.B.addUpdateListener(a.J),a.B.addMediaListener(a.G),a.B.media.length&&a.Gm(a.B.media[0]))},GDa=function(a){var b=a.A.media,c=a.A.customData;
if(b&&c){var d=r8(a);b.contentId!=d.videoId&&A7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.o=c.playerState;l8(d,a.A.getEstimatedTime());t8(a,d)}else A7("CP","No cast media video. Ignoring state update.")},w8=function(a,b,c){return(0,g.A)(function(a){this.jc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.jc("Retrying "+b+" using MDx browser channel."),v8(this,b,c))},a)},x8=function(a,b,c){g.LF.call(this);
this.D=window.NaN;this.O=!1;this.K=this.J=this.L=this.M=window.NaN;this.T=[];this.C=this.G=this.B=this.fb=this.o=null;this.sa=a;this.T.push(g.uF(window,"beforeunload",(0,g.A)(this.rK,this)));this.A=[];this.fb=new i8;this.ba=b.id;this.o=HDa(this,c);this.o.subscribe("handlerOpened",this.tR,this);this.o.subscribe("handlerClosed",this.qR,this);this.o.subscribe("handlerError",this.rR,this);this.o.subscribe("handlerMessage",this.sR,this);UCa(this.o,b.token);this.subscribe("remoteQueueChange",function(){var a=
this.fb.videoId;g.XG()&&g.UG("yt-remote-session-video-id",a)},this)},y8=function(a){A7("conn",a)},HDa=function(a,b){return new u7(x7(a.sa,"/bc"),b)},z8=function(a,b){a.V("proxyStateChange",b)},IDa=function(a){a.D=g.$D((0,g.A)(function(){y8("Connecting timeout");
this.F(1)},a),2E4)},A8=function(a){g.bE(a.D);
a.D=window.NaN},B8=function(a){g.bE(a.M);
a.M=window.NaN},JDa=function(a){C8(a);
a.L=g.$D((0,g.A)(function(){D8(this,"getNowPlaying")},a),2E4)},C8=function(a){g.bE(a.L);
a.L=window.NaN},LDa=function(a,b){b&&(A8(a),B8(a));
b==(v7(a.o)&&(0,window.isNaN)(a.D))?b&&(z8(a,1),D8(a,"getSubtitlesTrack")):b?(a.Z()&&a.fb.reset(),z8(a,1),D8(a,"getNowPlaying"),KDa(a)):a.F(1)},MDa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.fb.videoId&&(g.Zb(b.params)?a.fb.A=null:a.fb.A=b.params,a.V("remotePlayerChange"))},NDa=function(a,b){var c=b.params.videoId||b.params.video_id,d=(0,window.parseInt)(b.params.currentIndex,10);
a.fb.listId=b.params.listId||a.fb.listId;n8(a.fb,c,d);a.V("remoteQueueChange")},PDa=function(a,b){b.params=b.params||{};
NDa(a,b);ODa(a,b);a.V("autoplayDismissed")},ODa=function(a,b){var c=(0,window.parseInt)(b.params.currentTime||b.params.current_time,10);
l8(a.fb,(0,window.isNaN)(c)?0:c);c=(0,window.parseInt)(b.params.state,10);c=(0,window.isNaN)(c)?-1:c;-1==c&&-1E3==a.fb.o&&(c=-1E3);a.fb.o=c;c=Number(b.params.loadedTime);a.fb.K=(0,window.isNaN)(c)?0:c;c=Number(b.params.duration);a.fb.J=(0,window.isNaN)(c)?0:c;c=a.fb;var d=Number(b.params.liveIngestionTime);c.C=d;c.F=(0,window.isNaN)(d)?!1:!0;c=a.fb;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.D=(0,window.isNaN)(d)?0:d;c.B=(0,window.isNaN)(e)?0:e;1==a.fb.o?JDa(a):C8(a);
a.V("remotePlayerChange")},QDa=function(a,b){if(-1E3!=a.fb.o){var c=1085;
switch((0,window.parseInt)(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.fb.o=c;c=(0,window.parseInt)(b.params.currentTime,10);l8(a.fb,(0,window.isNaN)(c)?0:c);a.V("remotePlayerChange")}},RDa=function(a,b){var c="true"==b.params.muted;
a.fb.volume=(0,window.parseInt)(b.params.volume,10);a.fb.muted=c;a.V("remotePlayerChange")},SDa=function(a,b){a.G=b.params.videoId;
a.V("nowAutoplaying",(0,window.parseInt)(b.params.timeout,10))},TDa=function(a,b){var c="true"==b.params.hasNext;
a.fb.dg="true"==b.params.hasPrevious;a.fb.hasNext=c;a.V("previousNextChange")},KDa=function(a){g.bE(a.K);
a.K=g.$D((0,g.A)(a.F,a,1),864E5)},D8=function(a,b,c){c?y8("Sending: action="+b+", params="+g.Dg(c)):y8("Sending: action="+b);
a.o.sendMessage(b,c)},E8=function(a){E7.call(this,"ScreenServiceProxy");
this.ld=a;this.A=[];this.A.push(this.ld.$_s("screenChange",(0,g.A)(this.sX,this)));this.A.push(this.ld.$_s("onlineScreenChange",(0,g.A)(this.qT,this)))},YDa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.UD("MDX_CONFIG")||b;ZBa();M6();F8||(F8=new w7(b?b.loungeApiHost:void 0),gCa()&&(F8.o="/api/loungedev"));G8||(G8=g.y("yt.mdx.remote.deferredProxies_")||[],g.ua("yt.mdx.remote.deferredProxies_",G8,void 0));UDa();var c=H8();if(!c){var d=new N7(F8);g.ua("yt.mdx.remote.screenService_",d,void 0);c=H8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);yDa(a,d,function(a){a?I8()&&h8(I8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.aG("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.y("yt.mdx.remote.initialized_")&&(g.ua("yt.mdx.remote.initialized_",!0,void 0),J8("Initializing: "+g.Dg(b)),K8.push(g.XF("yt-remote-cast2-availability-change",function(){g.aG("yt-remote-receiver-availability-change")})),K8.push(g.XF("yt-remote-cast2-receiver-selected",function(){L8(null);
g.aG("yt-remote-auto-connect","cast-selector-receiver")})),K8.push(g.XF("yt-remote-cast2-receiver-resumed",function(){g.aG("yt-remote-receiver-resumed","cast-selector-receiver")})),K8.push(g.XF("yt-remote-cast2-session-change",VDa)),K8.push(g.XF("yt-remote-connection-change",function(a){a?h8(I8(),"YouTube TV"):M8()||(h8(null,null),BDa())})),a=N8(),b.isAuto&&(a.id+="#dial"),g.RF("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),J8(" -- with channel params: "+
g.Dg(a)),WDa(a),c.start(),I8()||XDa())},$Da=function(){var a=ZDa();
e8()&&g.VG("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},ZDa=function(){var a=H8().ld.$_gos();
var b=O8();b&&P8()&&(H6(a,b)||a.push(b));return YBa(a)},Q8=function(){var a=aEa();
!a&&e8()&&ADa()&&(a={key:"cast-selector-receiver",name:ADa()});return a},aEa=function(){var a=ZDa(),b=O8();
b||(b=M8());return g.Ka(a,function(a){return b&&D6(b,a.key)?!0:!1})},O8=function(){var a=I8();
if(!a)return null;var b=H8().se();return I6(b,a)},VDa=function(a){J8("remote.onCastSessionChange_: "+E6(a));
if(a){var b=O8();b&&b.id==a.id?h8(b.id,"YouTube TV"):(b&&R8(),S8(a,1))}else P8()&&R8()},R8=function(){f8()?c8().stopSession():a8("stopSession called before API ready.");
var a=P8();a&&(a.disconnect(1),T8(null))},U8=function(){var a=P8();
return!!a&&3!=a.getProxyState()},J8=function(a){A7("remote",a)},H8=function(){if(!V8){var a=g.y("yt.mdx.remote.screenService_");
V8=a?new E8(a):null}return V8},I8=function(){return g.y("yt.mdx.remote.currentScreenId_")},bEa=function(a){g.ua("yt.mdx.remote.currentScreenId_",a,void 0)},cEa=function(){return g.y("yt.mdx.remote.connectData_")},L8=function(a){g.ua("yt.mdx.remote.connectData_",a,void 0)},P8=function(){return g.y("yt.mdx.remote.connection_")},T8=function(a){var b=P8();
L8(null);a||bEa("");g.ua("yt.mdx.remote.connection_",a,void 0);G8&&((0,g.C)(G8,function(b){b(a)}),G8.length=0);
b&&!a?g.aG("yt-remote-connection-change",!1):!b&&a&&g.aG("yt-remote-connection-change",!0)},M8=function(){var a=g.XG();
if(!a)return null;var b=H8().se();return I6(b,a)},S8=function(a,b){O8()&&O8();
bEa(a.id);var c=new x8(F8,a,N8());c.connect(b,cEa());c.subscribe("beforeDisconnect",function(a){g.aG("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){P8()&&T8(null)});
T8(c)},XDa=function(){var a=M8();
a?(J8("Resume connection to: "+E6(a)),S8(a,0)):(N6(),BDa(),J8("Skipping connecting because no session screen found."))},UDa=function(){var a=N8();
if(g.Zb(a)){a=L6();var b=g.VG("yt-remote-session-name")||"",c=g.VG("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.ua("yt.mdx.remote.channelParams_",a,void 0)}},N8=function(){return g.y("yt.mdx.remote.channelParams_")||{}},WDa=function(a){a?(g.UG("yt-remote-session-app",a.app),g.UG("yt-remote-session-name",a.name)):(g.WG("yt-remote-session-app"),g.WG("yt-remote-session-name"));
g.ua("yt.mdx.remote.channelParams_",a,void 0)},W8=function(a,b,c){g.M.call(this);
this.H=a;this.A=b;this.B=new g.IF(this);g.N(this,this.B);this.B.R(b,"onCaptionsTrackListChanged",this.IS);this.B.R(b,"captionschanged",this.nR);this.B.R(b,"captionssettingschanged",this.oF);this.B.R(b,"videoplayerreset",this.Pp);this.B.R(b,"mdxautoplaycancel",this.yJ);this.T=this.B.R(b,"onVolumeChange",this.pD);this.G=!1;this.o=c;c.subscribe("proxyStateChange",this.CD,this);c.subscribe("remotePlayerChange",this.Jm,this);c.subscribe("remoteQueueChange",this.Pp,this);c.subscribe("autoplayUpNext",this.aD,
this);c.subscribe("previousNextChange",this.zD,this);c.subscribe("nowAutoplaying",this.rD,this);c.subscribe("autoplayDismissed",this.ZC,this);this.suggestion=null;this.J=new g.yP(64);this.C=new g.bu(this.jF,500,this);g.N(this,this.C);this.D=new g.bu(this.kF,1E3,this);g.N(this,this.D);this.L=new V6(this.TW,0,this);g.N(this,this.L);this.F={};this.M=new g.bu(this.KF,1E3,this);g.N(this,this.M);this.K=new g.$k(this.lP,1E3,this);g.N(this,this.K);this.O=g.z;this.oF();this.Pp();this.Jm()},X8=function(a,b){var c=
a.H,d=a.A.getVideoData().lengthSeconds;
c.J=b||0;c.o.V("progresssync",b,d)},dEa=function(a){X8(a,0);
a.C.stop();Y8(a,new g.yP(64))},$8=function(a,b){if(Z8(a)&&!a.G){var c=null;
b&&(c={style:a.A.Ti()},g.gc(c,b));a.o.XE(a.A.getVideoData(1).videoId,c);a.F=r8(a.o).A}},a9=function(a,b){var c=a.A.kg();
if(c){var d=c.qe();var e=c.listId.toString()}var f=a.A.getVideoData(1);c=a.o;var k=f.videoId,l=d;d=f.playerParams;var m=f.dk;f=OBa(f);var n=r8(c);l=l||0;var p={videoId:k,currentIndex:l};n8(n,k,l);g.v(b)&&(l8(n,b),p.currentTime=b);g.v(e)&&(p.listId=e);null!=d&&(p.playerParams=d);null!=m&&(p.clickTrackingParams=m);null!=f&&(p.locationInfo=g.Dg(f));v8(c,"setPlaylist",p);e||t8(c,n);Y8(a,new g.yP(1))},eEa=function(a,b){if(b){var c=a.A.Ac("captions","tracklist",{DA:1});
c&&c.length?(a.A.Td("captions","track",b),a.G=!1):(a.A.uk("captions"),a.G=!0)}else a.A.Td("captions","track",{})},Z8=function(a){return r8(a.o).videoId==a.A.getVideoData(1).videoId},Y8=function(a,b){a.D.stop();
var c=a.J;if(!g.DP(c,b)){var d=g.X(b,2);d!=g.X(a.J,2)&&g.zU(a.A,d);a.J=b;fEa(a.H,c,b)}},b9=function(a){g.W.call(this,{I:"div",
N:"ytp-remote",P:[{I:"div",N:"ytp-remote-display-status",P:[{I:"div",N:"ytp-remote-display-status-icon",P:[g.Hpa()]},{I:"div",N:"ytp-remote-display-status-text",ca:"{{statustext}}"}]}]});this.A=new g.pV(this,250);g.N(this,this.A);this.C=a;this.R(a,"presentingplayerstatechange",this.D);gEa(this,g.wU(a))},gEa=function(a,b){if(3==a.C.Ra()){var c={RECEIVER_NAME:a.C.Ac("remote","currentReceiver").name};
c=g.X(b,128)?g.t0('\u041e\u0448\u0438\u0431\u043a\u0430 \u043d\u0430 \u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u0435 "$RECEIVER_NAME"',c):b.rb()||g.X(b,4)?g.t0('\u0412\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0434\u0435\u043d\u0438\u0435 \u043d\u0430 \u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u0435 "$RECEIVER_NAME"',c):g.t0('\u0423\u0441\u0442\u0430\u043d\u043e\u0432\u043b\u0435\u043d\u043e \u043f\u043e\u0434\u043a\u043b\u044e\u0447\u0435\u043d\u0438\u0435 \u043a \u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u0443 "$RECEIVER_NAME"',
c);a.updateValue("statustext",c);a.A.show()}else a.A.hide()},c9=function(a,b){g.zZ.call(this,"\u0412\u044b\u0431\u0435\u0440\u0438\u0442\u0435 \u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u043e \u0434\u043b\u044f \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0430",0,a,b);
this.A=a;this.J={};this.R(a,"onMdxReceiversChange",this.L);this.R(a,"presentingplayerstatechange",this.L);this.L()},d9=function(a){g.WU.call(this,a);
this.B={key:G6(),name:"\u042d\u0442\u043e\u0442 \u043a\u043e\u043c\u043f\u044c\u044e\u0442\u0435\u0440"};this.D=null;this.F=[];this.K=this.A=null;this.H=[this.B];this.C=this.B;this.G=new g.yP(64);this.J=0;if(!g.aN(g.Y(this.o))){a=this.o;var b=g.MH(a);b&&(b=b.mp())&&(b=new c9(a,b),g.N(this,b));b=new b9(a);g.N(this,b);g.PU(a,b.element,4)}},fEa=function(a,b,c){a.G=c;
a.o.V("presentingplayerstatechange",new g.IP(c,b))},e9=function(a,b){if(b.key!=a.C.key)if(b.key==a.B.key)R8();
else{a.C=b;var c=a.o.getPlaylistId();var d=a.o.getVideoData(1);var e=d.videoId;if(c||e){var f=a.o.kg();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.bc(l).videoId}else k=[e];f=a.o.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.dk,index:Math.max(a.o.GB(),0),currentTime:0==f?void 0:f};(d=OBa(d))&&(c.locationInfo=d);d=c}else d=null;J8("Connecting to: "+g.Dg(b));"cast-selector-receiver"==b.key?(L8(d||null),f8()?c8().setLaunchParams(d||null):
a8("setLaunchParams called before ready.")):!d&&U8()&&I8()==b.key?g.aG("yt-remote-connection-change",!0):(R8(),L8(d||null),d=H8().se(),(d=I6(d,b.key))&&S8(d,1))}},vCa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},e7={"'":"\\'"},hEa={},UBa={IY:"atp",m3:"ska",B2:"que",L1:"mus",g3:"sus",Q_:"dsp"};
B6.prototype.Zn=function(){var a=new B6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.B=this.B;a.A=this.A;a.o=this.o};
var O6,K6="",S6=P6("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",nCa=P6("loadCastFramework")||P6("loadCastApplicationFramework"),xDa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.B(V6,g.M);g.h=V6.prototype;g.h.mK=function(a){this.C=arguments;this.o=!1;this.Fa?this.B=(0,g.G)()+this.wd:this.Fa=g.xg(this.D,this.wd)};
g.h.stop=function(){this.Fa&&(g.yg(this.Fa),this.Fa=null);this.B=null;this.o=!1;this.C=[]};
g.h.pause=function(){++this.A};
g.h.resume=function(){this.A&&(--this.A,!this.A&&this.o&&(this.o=!1,this.F.apply(null,this.C)))};
g.h.X=function(){this.stop();V6.ea.X.call(this)};
g.h.nK=function(){this.B?(this.Fa=g.xg(this.D,this.B-(0,g.G)()),this.B=null):(this.Fa=null,this.A?this.o=!0:(this.o=!1,this.F.apply(null,this.C)))};W6.prototype.stringify=function(a){return g.x.JSON.stringify(a,void 0)};
W6.prototype.parse=function(a){return g.x.JSON.parse(a,void 0)};g.h=X6.prototype;g.h.zi=null;g.h.Jf=!1;g.h.dl=null;g.h.Cw=null;g.h.Lk=null;g.h.Uj=null;g.h.th=null;g.h.Qh=null;g.h.bj=null;g.h.Tc=null;g.h.fn=0;g.h.Kf=null;g.h.Rq=null;g.h.uh=null;g.h.Sl=-1;g.h.CE=!0;g.h.hi=!1;g.h.Us=0;g.h.bq=null;var tCa={},$6={};g.h=X6.prototype;g.h.setTimeout=function(a){this.C=a};
g.h.KV=function(a){a=a.target;var b=this.bq;b&&3==g.lx(a)?b.Sj():this.UF(a)};
g.h.UF=function(a){try{if(a==this.Tc)a:{var b=g.lx(this.Tc),c=this.Tc.A,d=this.Tc.getStatus();if(g.yd&&!g.sc(10)||g.Ad&&!g.rc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.gf&&!g.px(this.Tc))break a;this.hi||4!=b||7==c||(8==c||0>=d?this.o.Df(3):this.o.Df(2));g7(this);var e=this.Tc.getStatus();this.Sl=e;var f=g.px(this.Tc);(this.Jf=200==e)?(4==b&&c7(this),this.D?(uCa(this,b,f),g.gf&&this.Jf&&3==b&&(this.Y.W(this.A,"tick",this.GV),this.A.start())):b7(this,f),this.Jf&&!this.hi&&(4==b?this.o.Np(this):
(this.Jf=!1,Z6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.uh=3,a7(13)):(this.uh=0,a7(14)),c7(this),d7(this))}}catch(k){this.Tc&&g.px(this.Tc)}finally{}};
g.h.GV=function(){var a=g.lx(this.Tc),b=g.px(this.Tc);this.fn<b.length&&(g7(this),uCa(this,a,b),this.Jf&&4!=a&&Z6(this))};
g.h.SU=function(a){f7((0,g.A)(this.RU,this,a),0)};
g.h.RU=function(a){this.hi||(g7(this),b7(this,a),Z6(this))};
g.h.LD=function(a){f7((0,g.A)(this.QU,this,a),0)};
g.h.QU=function(a){this.hi||(c7(this),this.Jf=a,this.o.Np(this),this.o.Df(4))};
g.h.cancel=function(){this.hi=!0;c7(this)};
g.h.iV=function(){this.dl=null;var a=(0,g.G)();0<=a-this.Cw?(2!=this.Uj&&this.o.Df(3),c7(this),this.uh=2,a7(18),d7(this)):xCa(this,this.Cw-a)};g.h=ACa.prototype;g.h.Ss=null;g.h.Ae=null;g.h.cq=!1;g.h.Uz=null;g.h.po=null;g.h.Zt=null;g.h.Ts=null;g.h.Se=null;g.h.Kg=-1;g.h.Rl=null;g.h.rl=null;g.h.connect=function(a){this.Ts=a;a=i7(this.o,null,this.Ts);a7(3);this.Uz=(0,g.G)();var b=this.o.H;null!=b?(this.Rl=b[0],(this.rl=b[1])?(this.Se=1,BCa(this)):(this.Se=2,k7(this))):(A6(a,"MODE","init"),this.Ae=new X6(this,void 0,void 0,void 0),this.Ae.zi=this.Ss,Y6(this.Ae,a,!1,null,!0),this.Se=0)};
g.h.zJ=function(a){if(a)this.Se=2,k7(this);else{a7(4);var b=this.o;b.Zf=b.jh.Kg;r7(b,9)}a&&this.Df(2)};
g.h.ls=function(a){return this.o.ls(a)};
g.h.abort=function(){this.Ae&&(this.Ae.cancel(),this.Ae=null);this.Kg=-1};
g.h.Tz=function(){return!1};
g.h.DD=function(a,b){this.Kg=a.Sl;if(0==this.Se)if(b){try{var c=this.A.parse(b)}catch(d){c=this.o;c.Zf=this.Kg;r7(c,2);return}this.Rl=c[0];this.rl=c[1]}else c=this.o,c.Zf=this.Kg,r7(c,2);else if(2==this.Se)if(this.cq)a7(7),this.Zt=(0,g.G)();else if("11111"==b){if(a7(6),this.cq=!0,this.po=(0,g.G)(),c=this.po-this.Uz,!g.yd||g.sc(10)||500>c)this.Kg=200,this.Ae.cancel(),a7(12),j7(this.o,this,!0)}else a7(8),this.po=this.Zt=(0,g.G)(),this.cq=!1};
g.h.Np=function(){this.Kg=this.Ae.Sl;if(this.Ae.Jf)0==this.Se?this.rl?(this.Se=1,BCa(this)):(this.Se=2,k7(this)):2==this.Se&&((!g.yd||g.sc(10)?!this.cq:200>this.Zt-this.po)?(a7(11),j7(this.o,this,!1)):(a7(12),j7(this.o,this,!0)));else{0==this.Se?a7(9):2==this.Se&&a7(10);var a=this.o;a.Zf=this.Kg;r7(a,2)}};
g.h.Tm=function(){return this.o.Tm()};
g.h.isActive=function(){return this.o.isActive()};
g.h.Df=function(a){this.o.Df(a)};g.h=l7.prototype;g.h.Dl=null;g.h.fe=null;g.h.xc=null;g.h.Rs=null;g.h.to=null;g.h.hy=null;g.h.Go=null;g.h.Dm=0;g.h.FQ=0;g.h.ud=null;g.h.lh=null;g.h.zg=null;g.h.mi=null;g.h.jh=null;g.h.Qq=null;g.h.ik=-1;g.h.RA=-1;g.h.Zf=-1;g.h.Jj=0;g.h.wj=0;g.h.ji=8;var s7=new g.Gf;g.B(DCa,g.ef);g.B(ECa,g.ef);g.B(FCa,g.ef);g.h=l7.prototype;g.h.connect=function(a,b,c,d,e){a7(0);this.Rs=b;this.Dl=c||{};d&&g.v(e)&&(this.Dl.OSID=d,this.Dl.OAID=e);this.F?(f7((0,g.A)(this.Gy,this,a),100),JCa(this)):this.Gy(a)};
g.h.Gy=function(a){this.jh=new ACa(this);this.jh.Ss=null;this.jh.A=this.D;this.jh.connect(a)};
g.h.Tz=function(){return 0==this.o};
g.h.JD=function(a){this.lh=null;MCa(this,a)};
g.h.ID=function(){this.zg=null;this.xc=new X6(this,this.B,"rpc",this.G);this.xc.zi=null;this.xc.Us=0;var a=this.hy.clone();g.Im(a,"RID","rpc");g.Im(a,"SID",this.B);g.Im(a,"CI",this.Qq?"0":"1");g.Im(a,"AID",this.ik);m7(this,a);if(!g.yd||g.sc(10))g.Im(a,"TYPE","xmlhttp"),Y6(this.xc,a,!0,this.Go,!1);else{g.Im(a,"TYPE","html");var b=this.xc,c=!!this.Go;b.Uj=3;b.th=z6(a.clone());wCa(b,c)}};
g.h.DD=function(a,b){if(0!=this.o&&(this.xc==a||this.fe==a))if(this.Zf=a.Sl,this.fe==a&&3==this.o)if(7<this.ji){try{var c=this.D.parse(b)}catch(f){c=null}if(g.za(c)&&3==c.length)if(0==c[0])a:{if(!this.zg){if(this.xc)if(this.xc.Lk+3E3<this.fe.Lk)o7(this),this.xc.cancel(),this.xc=null;else break a;q7(this);a7(19)}}else this.RA=c[1],0<this.RA-this.ik&&37500>c[2]&&this.Qq&&0==this.wj&&!this.mi&&(this.mi=f7((0,g.A)(this.iR,this),6E3));else r7(this,11)}else b!=hEa.LZ.o&&r7(this,11);else if(this.xc==a&&
o7(this),!g.E(b)){c=this.D.parse(b);g.za(c);for(var d=0;d<c.length;d++){var e=c[d];this.ik=e[0];e=e[1];2==this.o?"c"==e[0]?(this.B=e[1],this.Go=e[2],e=e[3],null!=e?this.ji=e:this.ji=6,this.o=3,this.ud&&this.ud.wy(),this.hy=i7(this,this.Tm()?this.Go:null,this.Rs),NCa(this)):"stop"==e[0]&&r7(this,7):3==this.o&&("stop"==e[0]?r7(this,7):"noop"!=e[0]&&this.ud&&this.ud.vy(e),this.wj=0)}}};
g.h.iR=function(){null!=this.mi&&(this.mi=null,this.xc.cancel(),this.xc=null,q7(this),a7(20))};
g.h.Np=function(a){if(this.xc==a){o7(this);this.xc=null;var b=2}else if(this.fe==a)this.fe=null,b=1;else return;this.Zf=a.Sl;if(0!=this.o)if(a.Jf)1==b?(b=(0,g.G)()-a.Lk,s7.dispatchEvent(new ECa(s7,a.bj?a.bj.length:0,b,this.Jj)),n7(this),this.C.length=0):NCa(this);else{var c=a.uh,d;if(!(d=3==c||7==c||0==c&&0<this.Zf)){if(d=1==b)this.fe||this.lh||1==this.o||2<=this.Jj?d=!1:(this.lh=f7((0,g.A)(this.JD,this,a),OCa(this,this.Jj)),this.Jj++,d=!0);d=!(d||2==b&&q7(this))}if(d)switch(c){case 1:r7(this,5);
break;case 4:r7(this,10);break;case 3:r7(this,6);break;case 7:r7(this,12);break;default:r7(this,2)}}};
g.h.UJ=function(a){if(!g.Oa(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.h.EW=function(a){a?a7(2):(a7(1),PCa(this,8))};
g.h.ls=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.fx;a.H=!1;return a};
g.h.isActive=function(){return!!this.ud&&this.ud.isActive(this)};
g.h.Df=function(a){s7.dispatchEvent(new FCa(s7,a))};
g.h.Tm=function(){return!(!g.yd||g.sc(10))};
g.h=QCa.prototype;g.h.wy=function(){};
g.h.vy=function(){};
g.h.uy=function(){};
g.h.Tr=function(){};
g.h.Bz=function(){return{}};
g.h.isActive=function(){return!0};g.B(t7,g.M);g.h=t7.prototype;g.h.JU=function(){this.wd=Math.min(3E5,2*this.wd);this.B();this.A&&this.start()};
g.h.start=function(){var a=this.wd+15E3*Math.random();g.cu(this.o,a);this.A=(0,g.G)()+a};
g.h.stop=function(){this.o.stop();this.A=0};
g.h.isActive=function(){return this.o.isActive()};
g.h.reset=function(){this.o.stop();this.wd=5E3};g.B(u7,QCa);g.h=u7.prototype;g.h.subscribe=function(a,b,c){return this.B.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.B.unsubscribe(a,b,c)};
g.h.Yd=function(a){return this.B.Yd(a)};
g.h.V=function(a,b){return this.B.V.apply(this.B,arguments)};
g.h.dispose=function(){this.K||(this.K=!0,g.cf(this.B),TCa(this),g.cf(this.A),this.A=null)};
g.h.ma=function(){return this.K};
g.h.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.J="";this.A.stop();this.D=a||null;this.C=b||0;a=this.L+"/test";b=this.L+"/bind";var d=new l7(c?c.firstTestResults:null,c?c.secondTestResults:null,this.M),e=this.o;e&&(e.ud=null);d.ud=this;this.o=d;e?this.o.connect(a,b,this.F,e.B,e.ik):c?this.o.connect(a,b,this.F,c.sessionId,c.arrayId):this.o.connect(a,b,this.F)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.gc(c,b);this.A.isActive()||2==(this.o?this.o.o:0)?this.G.push(c):v7(this)&&KCa(this.o,c)};
g.h.wy=function(){this.A.reset();this.D=null;this.C=0;if(this.G.length){var a=this.G;this.G=[];for(var b=0,c=a.length;b<c;++b)KCa(this.o,a[b])}this.V("handlerOpened")};
g.h.uy=function(a){var b=2==a&&401==this.o.Zf;4==a||b||this.A.start();this.V("handlerError",a)};
g.h.Tr=function(a){if(!this.A.isActive())this.V("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.G.push(d)}};
g.h.Bz=function(){var a={v:2};this.J&&(a.gsessionid=this.J);0!=this.C&&(a.ui=""+this.C);0!=this.H&&(a.ui=""+this.H);this.D&&g.gc(a,this.D);return a};
g.h.vy=function(a){"S"==a[0]?this.J=a[1]:"gracefulReconnect"==a[0]?(this.A.start(),ICa(this.o)):this.V("handlerMessage",new RCa(a[0],a[1]))};
g.h.oX=function(){this.A.isActive();var a=this.o,b=0;a.xc&&b++;a.fe&&b++;0!=b||this.connect(this.D,this.C)};w7.prototype.C=function(a,b,c,d){b?a(d):a({text:c.responseText})};
w7.prototype.B=function(a,b){a(Error("Request error: "+b.status))};
w7.prototype.D=function(a){a(Error("request timed out"))};var aDa=(0,g.G)(),z7=null,C7=Array(50),B7=-1,D7=!1;g.B(E7,g.LF);E7.prototype.se=function(){return this.o};
E7.prototype.contains=function(a){return!!H6(this.o,a)};
E7.prototype.get=function(a){return a?I6(this.o,a):null};
E7.prototype.info=function(a){A7(this.G,a)};g.B(F7,g.LF);var iEa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=F7.prototype;g.h.start=function(){!this.o&&(0,window.isNaN)(this.Fa)&&this.ZF()};
g.h.stop=function(){this.o&&(this.o.abort(),this.o=null);(0,window.isNaN)(this.Fa)||(g.bE(this.Fa),this.Fa=window.NaN)};
g.h.X=function(){this.stop();F7.ea.X.call(this)};
g.h.ZF=function(){this.Fa=window.NaN;this.o=g.qE(x7(this.F,"/pairing/get_screen"),{method:"POST",Qb:{pairing_code:this.D},timeout:5E3,onSuccess:(0,g.A)(this.qX,this),onError:(0,g.A)(this.pX,this),Bd:(0,g.A)(this.rX,this)})};
g.h.qX=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.B;c.name=this.C;this.V("pairingComplete",new C6(c))};
g.h.pX=function(a){this.o=null;a.status&&404==a.status?this.A>=iEa.length?this.V("pairingFailed",Error("DIAL polling timed out")):(a=iEa[this.A],this.Fa=g.$D((0,g.A)(this.ZF,this),a),this.A++):this.V("pairingFailed",Error("Server error "+a.status))};
g.h.rX=function(){this.o=null;this.V("pairingFailed",Error("Server not responding"))};g.B(H7,E7);g.h=H7.prototype;g.h.start=function(){G7(this)&&this.V("screenChange");!g.VG("yt-remote-lounge-token-expiration")&&eDa(this);g.bE(this.A);this.A=g.$D((0,g.A)(this.start,this),1E4)};
g.h.add=function(a,b){G7(this);bDa(this,a);I7(this,!1);this.V("screenChange");b(a);a.token||eDa(this)};
g.h.remove=function(a,b){var c=G7(this);dDa(this,a)&&(I7(this,!1),c=!0);b(a);c&&this.V("screenChange")};
g.h.Kq=function(a,b,c,d){var e=G7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,I7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.V("screenChange")};
g.h.X=function(){g.bE(this.A);H7.ea.X.call(this)};
g.h.AK=function(a){G7(this);var b=this.o.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}I7(this,!b);b&&A7(this.G,"Missed "+b+" lounge tokens.")};
g.h.zK=function(a){A7(this.G,"Requesting lounge tokens failed: "+a)};g.B(K7,g.LF);g.h=K7.prototype;g.h.start=function(){var a=(0,window.parseInt)(g.VG("yt-remote-fast-check-period")||"0",10);(this.C=(0,g.G)()-144E5<a?0:a)?M7(this):(this.C=(0,g.G)()+3E5,g.UG("yt-remote-fast-check-period",this.C),this.Pv())};
g.h.isEmpty=function(){return g.Zb(this.o)};
g.h.update=function(){J7("Updating availability on schedule.");var a=this.F(),b=g.Lb(this.o,function(b,d){return b&&!!I6(a,d)},this);
L7(this,b)};
g.h.X=function(){g.bE(this.B);this.B=window.NaN;this.A&&(this.A.abort(),this.A=null);K7.ea.X.call(this)};
g.h.Pv=function(){g.bE(this.B);this.B=window.NaN;this.A&&this.A.abort();var a=hDa(this);if(g.Ob(a)){var b=x7(this.D,"/pairing/get_screen_availability");this.A=y7(this.D,b,{lounge_token:g.Rb(a).join(",")},(0,g.A)(this.rU,this,a),(0,g.A)(this.qU,this))}else L7(this,{}),M7(this)};
g.h.rU=function(a,b){this.A=null;var c=g.Rb(hDa(this));if(g.ib(c,g.Rb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;L7(this,d);M7(this)}else this.jc("Changing Screen set during request."),this.Pv()};
g.h.qU=function(a){this.jc("Screen availability failed: "+a);this.A=null;M7(this)};
g.h.jc=function(a){A7("OnlineScreenService",a)};g.B(N7,E7);g.h=N7.prototype;g.h.start=function(){this.B.start();this.A.start();this.o.length&&(this.V("screenChange"),this.A.isEmpty()||this.V("onlineScreenChange"))};
g.h.add=function(a,b,c){this.B.add(a,b,c)};
g.h.remove=function(a,b,c){this.B.remove(a,b,c);this.A.update()};
g.h.Kq=function(a,b,c,d){this.B.contains(a)?this.B.Kq(a,b,c,d):(a="Updating name of unknown screen: "+a.name,A7(this.G,a),d(Error(a)))};
g.h.se=function(a){return a?this.o:g.Wa(this.o,(0,g.Ld)(this.C,function(a){return!this.contains(a)},this))};
g.h.aG=function(){return(0,g.Ld)(this.se(!0),function(a){return!!this.A.o[a.id]},this)};
g.h.bG=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new F7(this.F,a,b,c);f.subscribe("pairingComplete",(0,g.A)(function(a){g.cf(f);d(O7(this,a))},this));
f.subscribe("pairingFailed",function(a){g.cf(f);e(a)});
f.start();return(0,g.A)(f.stop,f)};
g.h.tX=function(a,b,c,d){g.qE(x7(this.F,"/pairing/get_screen"),{method:"POST",Qb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.A)(function(a,d){var e=new C6(d.screen||{});if(!e.name||lDa(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);lDa(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(O7(this,e))},this),
onError:(0,g.A)(function(a){d(Error("pairing request failed: "+a.status))},this),
Bd:(0,g.A)(function(){d(Error("pairing request timed out."))},this)})};
g.h.X=function(){g.cf(this.B);g.cf(this.A);N7.ea.X.call(this)};
g.h.PK=function(){mDa(this);this.V("screenChange");this.A.update()};
N7.prototype.dispose=N7.prototype.dispose;g.B(Q7,g.LF);g.h=Q7.prototype;g.h.Op=function(a){this.B=a;this.V("sessionScreen",this.B)};
g.h.ye=function(a){this.ma()||(a&&R7(this,""+a),this.B=null,this.V("sessionScreen",null))};
g.h.info=function(a){A7(this.M,a)};
g.h.dG=function(){return null};
g.h.Vv=function(a){var b=this.A;a?(b.displayStatus=new window.chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;window.chrome.cast.setReceiverDisplayStatus(b,(0,g.A)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.A)(function(){R7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.X=function(){this.Vv("");Q7.ea.X.call(this)};g.B(S7,Q7);g.h=S7.prototype;g.h.Uv=function(a){if(this.o){if(this.o==a)return;R7(this,"Overriding cast sesison with new session object");this.o.removeUpdateListener(this.F);this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D)}this.o=a;this.o.addUpdateListener(this.F);this.o.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.D);oDa(this)};
g.h.kk=function(a){this.info("launchWithParams no-op for Cast: "+g.Dg(a))};
g.h.stop=function(){this.o?this.o.stop((0,g.A)(function(){this.ye()},this),(0,g.A)(function(){this.ye(Error("Failed to stop receiver app."))},this)):this.ye(Error("Stopping cast device witout session."))};
g.h.Vv=g.z;g.h.X=function(){this.info("disposeInternal");g.bE(this.C);this.C=0;this.o&&(this.o.removeUpdateListener(this.F),this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D));this.o=null;S7.ea.X.call(this)};
g.h.uV=function(a,b){if(!this.ma())if(b){var c=g.$w(b);if(g.Ca(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Dg(c));switch(d){case "mdxSessionStatus":nDa(this,c.screenId);break;default:R7(this,"Unknown youtube message: "+d)}}else R7(this,"Unable to parse message.")}else R7(this,"No data in message.")};
g.h.Lz=function(a,b,c,d){kDa(this.J,this.A.label,a,this.A.friendlyName,(0,g.A)(function(e){e?b(e):0<=d?(R7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.$D((0,g.A)(this.Lz,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.dG=function(){return this.o};
g.h.uX=function(a){this.ma()||a||(R7(this,"Cast session died."),this.ye())};g.B(T7,Q7);g.h=T7.prototype;g.h.Uv=function(a){this.C=a;this.C.addUpdateListener(this.L)};
g.h.kk=function(a){this.D=a;this.G()};
g.h.stop=function(){this.o();this.o=g.z;g.bE(this.F);this.C?this.C.stop((0,g.A)(this.ye,this,null),(0,g.A)(this.ye,this,"Failed to stop DIAL device.")):this.ye()};
g.h.X=function(){this.o();this.o=g.z;g.bE(this.F);this.C&&this.C.removeUpdateListener(this.L);this.C=null;T7.ea.X.call(this)};
g.h.xX=function(a){this.ma()||a||(R7(this,"DIAL session died."),this.o(),this.o=g.z,this.ye())};
g.h.Nt=function(a){this.K=G6();if(this.D){var b=new window.chrome.cast.DialLaunchResponse(!0,qDa(this));a(b);pDa(this)}else this.G=(0,g.A)(function(){g.bE(this.F);this.G=g.z;this.F=window.NaN;var b=new window.chrome.cast.DialLaunchResponse(!0,qDa(this));a(b);pDa(this)},this),this.F=g.$D((0,g.A)(function(){this.G()},this),100)};
g.h.eM=function(a,b,c){kDa(this.J,this.H.receiver.label,a,this.A.friendlyName,(0,g.A)(function(a){a&&a.token?(this.Op(a),b(new window.chrome.cast.DialLaunchResponse(!1))):this.Nt(b,c)},this),(0,g.A)(function(a){R7(this,"Failed to get DIAL screen: "+a);
this.Nt(b,c)},this))};g.B(U7,Q7);U7.prototype.stop=function(){this.ye()};
U7.prototype.Uv=g.z;U7.prototype.kk=function(){g.bE(this.o);this.o=window.NaN;var a=I6(this.J.se(),this.A.label);a?this.Op(a):this.ye(Error("No such screen"))};
U7.prototype.X=function(){g.bE(this.o);this.o=window.NaN;U7.ea.X.call(this)};g.B(V7,g.LF);g.h=V7.prototype;
g.h.init=function(a,b){window.chrome.cast.timeout.requestSession=3E4;var c=new window.chrome.cast.SessionRequest(this.G);this.H||(c.dialRequest=new window.chrome.cast.DialRequest("YouTube"));var d=window.chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?window.chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:window.chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new window.chrome.cast.ApiConfig(c,(0,g.A)(this.FD,this),(0,g.A)(this.aU,this),d,e);c.customDialLaunchCallback=(0,g.A)(this.TR,this);window.chrome.cast.initialize(c,
(0,g.A)(function(){this.ma()||(window.chrome.cast.addReceiverActionListener(this.C),YCa(),this.A.subscribe("onlineScreenChange",(0,g.A)(this.cG,this)),this.B=sDa(this),window.chrome.cast.setCustomReceivers(this.B,g.z,(0,g.A)(function(a){this.jc("Failed to set initial custom receivers: "+g.Dg(a))},this)),this.V("yt-remote-cast2-availability-change",X7(this)),b(!0))},this),(0,g.A)(function(a){this.jc("Failed to initialize API: "+g.Dg(a));
b(!1)},this))};
g.h.lW=function(a,b){W7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.B;if(!a||c&&c.id!=a)W7("Unsetting old screen status: "+this.o.A.friendlyName),Y7(this,null)}if(a&&b){if(!this.o){c=I6(this.A.se(),a);if(!c){W7("setConnectedScreenStatus: Unknown screen.");return}var d=rDa(this,c);d||(W7("setConnectedScreenStatus: Connected receiver not custom..."),d=new window.chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM,this.B.push(d),
window.chrome.cast.setCustomReceivers(this.B,g.z,(0,g.A)(function(a){this.jc("Failed to set initial custom receivers: "+g.Dg(a))},this)));
W7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);Y7(this,new U7(this.A,d),!0)}this.o.Vv(b)}else W7("setConnectedScreenStatus: no screen.")};
g.h.mW=function(a){this.ma()?this.jc("Setting connection data on disposed cast v2"):this.o?this.o.kk(a):this.jc("Setting connection data without a session")};
g.h.wX=function(){this.ma()?this.jc("Stopping session on disposed cast v2"):this.o?(this.o.stop(),Y7(this,null)):W7("Stopping non-existing session")};
g.h.requestSession=function(){window.chrome.cast.requestSession((0,g.A)(this.FD,this),(0,g.A)(this.vU,this))};
g.h.X=function(){this.A.unsubscribe("onlineScreenChange",(0,g.A)(this.cG,this));window.chrome&&window.chrome.cast&&window.chrome.cast.removeReceiverActionListener(this.C);g.Ta(g.y("yt.mdx.remote.debug.handlers_")||[],VCa);g.cf(this.o);V7.ea.X.call(this)};
g.h.jc=function(a){A7("Controller",a)};
g.h.GD=function(a,b){this.o==a&&(b||Y7(this,null),this.V("yt-remote-cast2-session-change",b))};
g.h.UT=function(a,b){if(!this.ma())if(a)switch(a.friendlyName=window.chrome.cast.unescape(a.friendlyName),W7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case window.chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.A.label!=a.label)W7("onReceiverAction_: Stopping active receiver: "+this.o.A.friendlyName),this.o.stop();else{W7("onReceiverAction_: Casting to active receiver.");this.o.B&&this.V("yt-remote-cast2-session-change",this.o.B);break}switch(a.receiverType){case window.chrome.cast.ReceiverType.CUSTOM:Y7(this,
new U7(this.A,a));break;case window.chrome.cast.ReceiverType.DIAL:Y7(this,new T7(this.A,a,this.F));break;case window.chrome.cast.ReceiverType.CAST:Y7(this,new S7(this.A,a));break;default:this.jc("Unknown receiver type: "+a.receiverType)}break;case window.chrome.cast.ReceiverAction.STOP:this.o&&this.o.A.label==a.label?this.o.stop():this.jc("Stopping receiver w/o session: "+a.friendlyName)}else this.jc("onReceiverAction_ called without receiver.")};
g.h.TR=function(a){if(this.ma())return window.Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=window.chrome.cast.ReceiverType.DIAL&&(this.jc("Not DIAL receiver: "+b.friendlyName),b.receiverType=window.chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.A:null;if(!c||c.label!=b.label)return this.jc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),window.Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=window.chrome.cast.ReceiverType.DIAL){if(this.o.B)return W7("Reselecting dial screen."),
this.V("yt-remote-cast2-session-change",this.o.B),window.Promise.resolve(new window.chrome.cast.DialLaunchResponse(!1));this.jc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);Y7(this,new T7(this.A,b,this.F))}b=this.o;b.H=a;return b.H.appState==window.chrome.cast.DialAppState.RUNNING?new window.Promise((0,g.A)(b.eM,b,(b.H.extraData||{}).screenId||null)):new window.Promise((0,g.A)(b.Nt,b))};
g.h.FD=function(a){if(!this.ma()){W7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=window.chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==window.chrome.cast.ReceiverType.CAST)W7("Got resumed cast session before resumed mdx connection."),b.friendlyName=window.chrome.cast.unescape(b.friendlyName),Y7(this,new S7(this.A,b),!0);else{this.jc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.A,d=I6(this.A.se(),c.label);
d&&D6(d,b.label)&&c.receiverType!=window.chrome.cast.ReceiverType.CAST&&b.receiverType==window.chrome.cast.ReceiverType.CAST&&(W7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.cf(this.o),this.o=new S7(this.A,b),this.o.subscribe("sessionScreen",(0,g.A)(this.GD,this,this.o)),this.o.kk(null));this.o.Uv(a)}}};
g.h.vX=function(){return this.o?this.o.dG():null};
g.h.vU=function(a){this.ma()||(this.jc("Failed to estabilish a session: "+g.Dg(a)),a.code!=window.chrome.cast.ErrorCode.CANCEL&&Y7(this,null))};
g.h.aU=function(a){W7("Receiver availability updated: "+a);if(!this.ma()){var b=X7(this);this.D=a==window.chrome.cast.ReceiverAvailability.AVAILABLE;X7(this)!=b&&this.V("yt-remote-cast2-availability-change",X7(this))}};
g.h.cG=function(){this.ma()||(this.B=sDa(this),W7("Updating custom receivers: "+g.Dg(this.B)),window.chrome.cast.setCustomReceivers(this.B,g.z,(0,g.A)(function(){this.jc("Failed to set custom receivers.")},this)),this.V("yt-remote-cast2-availability-change",X7(this)))};
V7.prototype.setLaunchParams=V7.prototype.mW;V7.prototype.setConnectedScreenStatus=V7.prototype.lW;V7.prototype.stopSession=V7.prototype.wX;V7.prototype.getCastSession=V7.prototype.vX;V7.prototype.requestSession=V7.prototype.requestSession;V7.prototype.init=V7.prototype.init;V7.prototype.dispose=V7.prototype.dispose;var d8=[];g.h=i8.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";j8(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.o=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.A=a.trackData,this.dg=a.hasPrevious,this.hasNext=a.hasNext,this.H=a.playerTime,this.G=a.playerTimeAt,this.D=a.seekableStart,this.B=a.seekableEnd,this.J=a.duration,this.K=a.loadedTime,this.C=a.liveIngestionTime,this.F=!(0,window.isNaN)(this.C))};
g.h.rb=function(){return 1==this.o};
g.h.isAdPlaying=function(){return 1081==this.o};
g.h.getDuration=function(){return this.F?this.J+k8(this):this.J};
g.h.clone=function(){return new i8(o8(this))};g.B(q8,g.LF);g.h=q8.prototype;g.h.play=function(){1==this.o?(this.A?this.A.play(null,g.z,w8(this,"play")):v8(this,"play"),u8(this,1,m8(r8(this))),this.V("remotePlayerChange")):s8(this,this.play)};
g.h.pause=function(){1==this.o?(this.A?this.A.pause(null,g.z,w8(this,"pause")):v8(this,"pause"),u8(this,2,m8(r8(this))),this.V("remotePlayerChange")):s8(this,this.pause)};
g.h.YF=function(a){if(1==this.o){if(this.A){var b=r8(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.rb()||3==b.o?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.A.seek(c,g.z,w8(this,"seekTo",{newTime:a}))}else v8(this,"seekTo",{newTime:a});u8(this,3,a);this.V("remotePlayerChange")}else s8(this,g.Fa(this.YF,a))};
g.h.stop=function(){if(1==this.o){this.A?this.A.stop(null,g.z,w8(this,"stopVideo")):v8(this,"stopVideo");var a=r8(this);a.index=-1;a.videoId="";j8(a);t8(this,a);this.V("remotePlayerChange")}else s8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.o){var c=r8(this);if(this.B){if(c.volume!=a){var d=Math.round(a)/100;this.B.setReceiverVolumeLevel(d,(0,g.A)(function(){A7("CP","set receiver volume: "+d)},this),(0,g.A)(function(){this.jc("failed to set receiver volume.")},this))}c.muted!=b&&this.B.setReceiverMuted(b,(0,g.A)(function(){A7("CP","set receiver muted: "+b)},this),(0,g.A)(function(){this.jc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);v8(this,"setVolume",e)}c.muted=b;c.volume=a;t8(this,c)}else s8(this,g.Fa(this.setVolume,a,b))};
g.h.XE=function(a,b){if(1==this.o){var c=r8(this),d={videoId:a};b&&(c.A={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.Dg(b.style),g.gc(d,c.A));v8(this,"setSubtitlesTrack",d);t8(this,c)}else s8(this,g.Fa(this.XE,a,b))};
g.h.Iw=function(a,b){if(1==this.o){v8(this,"setAudioTrack",{videoId:a,audioTrackId:b.Kb.id});var c=r8(this);c.audioTrackId=b.Kb.id;t8(this,c)}else s8(this,g.Fa(this.Iw,a,b))};
g.h.XF=function(a,b){if(1==this.o){if(a&&b){var c=r8(this);n8(c,a,b);t8(this,c)}v8(this,"previous")}else s8(this,g.Fa(this.XF,a,b))};
g.h.WF=function(a,b){if(1==this.o){if(a&&b){var c=r8(this);n8(c,a,b);t8(this,c)}v8(this,"next")}else s8(this,g.Fa(this.WF,a,b))};
g.h.Zy=function(){1==this.o?v8(this,"dismissAutoplay"):s8(this,this.Zy)};
g.h.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.V("proxyStateChange",a,this.o)}q8.ea.dispose.call(this)};
g.h.X=function(){FDa(this);this.C=null;this.D.clear();p8(this,null);q8.ea.X.call(this)};
g.h.Jw=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.V("proxyStateChange",b,a);if(1==a)for(;!this.D.isEmpty();)g.tC(this.D).apply(this);else 3==a&&this.dispose()}};
g.h.PT=function(a,b){this.V(a,b)};
g.h.pR=function(a){if(!a)this.Gm(null),p8(this,null);else if(this.B.receiver.volume){a=this.B.receiver.volume;var b=r8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)A7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,t8(this,b)}};
g.h.Gm=function(a){A7("CP","Cast media: "+!!a);this.A&&this.A.removeUpdateListener(this.H);if(this.A=a)this.A.addUpdateListener(this.H),GDa(this),this.V("remotePlayerChange")};
g.h.oR=function(a){a?(GDa(this),this.V("remotePlayerChange")):this.Gm(null)};
g.h.CR=function(){var a=CDa();a&&p8(this,a)};
g.h.jc=function(a){A7("CP",a)};g.B(x8,g.LF);g.h=x8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.v(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.v(k)&&(l.currentIndex=k);c&&(this.fb.listId=c);this.fb.videoId=d;this.fb.index=k||0;this.fb.state=3;l8(this.fb,m);this.C="UNSUPPORTED";y8("Connecting with setPlaylist and params: "+g.Dg(l));this.o.connect({method:"setPlaylist",
params:g.Dg(l)},a,bCa())}else y8("Connecting without params"),this.o.connect({},a,bCa());IDa(this)};
g.h.dispose=function(){this.ma()||(this.V("beforeDispose"),z8(this,3));x8.ea.dispose.call(this)};
g.h.X=function(){A8(this);C8(this);B8(this);g.bE(this.J);this.J=window.NaN;g.bE(this.K);this.K=window.NaN;this.B=null;g.vF(this.T);this.T.length=0;this.o.dispose();x8.ea.X.call(this);this.C=this.G=this.A=this.fb=this.o=null};
g.h.rK=function(){this.F(2)};
g.h.tR=function(){y8("Channel opened");this.O&&(this.O=!1,B8(this),this.M=g.$D((0,g.A)(function(){y8("Timing out waiting for a screen.");this.F(1)},this),15E3));
fCa(SCa(this.o),this.ba)};
g.h.qR=function(){y8("Channel closed");(0,window.isNaN)(this.D)?N6(!0):N6();this.dispose()};
g.h.rR=function(a){N6();(0,window.isNaN)(this.H())?(y8("Channel error: "+a+" without reconnection"),this.dispose()):(this.O=!0,y8("Channel error: "+a+" with reconnection in "+this.H()+" ms"),z8(this,2))};
g.h.sR=function(a){a.params?y8("Received: action="+a.action+", params="+g.Dg(a.params)):y8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.$w(a.params.devices);this.A=(0,g.I)(a,function(a){return new B6(a)});
a=!!g.Ka(this.A,function(a){return"LOUNGE_SCREEN"==a.type});
LDa(this,a);break;case "loungeScreenDisconnected":g.Ua(this.A,function(a){return"LOUNGE_SCREEN"==a.type});
LDa(this,!1);break;case "remoteConnected":var b=new B6(g.$w(a.params.device));g.Ka(this.A,function(a){return b?a.id==b.id:!1})||g.Ra(this.A,b);
break;case "remoteDisconnected":b=new B6(g.$w(a.params.device));g.Ua(this.A,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":NDa(this,a);break;case "nowPlaying":PDa(this,a);break;case "onStateChange":ODa(this,a);break;case "onAdStateChange":QDa(this,a);break;case "onVolumeChanged":RDa(this,a);break;case "onSubtitlesTrackChanged":MDa(this,a);break;case "nowAutoplaying":SDa(this,a);break;case "autoplayDismissed":this.V("autoplayDismissed");break;case "autoplayUpNext":this.G=a.params.videoId||null;this.V("autoplayUpNext",this.G);break;case "onAutoplayModeChanged":this.C=
a.params.autoplayMode;this.V("autoplayModeChange",this.C);"DISABLED"==this.C&&this.V("autoplayDismissed");break;case "onHasPreviousNextChanged":TDa(this,a);break;case "requestAssistedSignIn":this.V("assistedSignInRequested",a.params.authCode);break;default:y8("Unrecognized action: "+a.action)}};
g.h.VV=function(){if(this.B){var a=this.B;this.B=null;this.fb.videoId!=a&&D8(this,"getNowPlaying")}};
x8.prototype.subscribe=x8.prototype.subscribe;x8.prototype.unsubscribeByKey=x8.prototype.Yd;x8.prototype.ia=function(){var a=3;this.ma()||(a=0,(0,window.isNaN)(this.H())?v7(this.o)&&(0,window.isNaN)(this.D)&&(a=1):a=2);return a};
x8.prototype.getProxyState=x8.prototype.ia;x8.prototype.F=function(a){y8("Disconnecting with "+a);A8(this);this.V("beforeDisconnect",a);1==a&&N6();TCa(this.o,a);this.dispose()};
x8.prototype.disconnect=x8.prototype.F;x8.prototype.ha=function(){var a=this.fb;this.B&&(a=this.fb.clone(),n8(a,this.B,a.index));return o8(a)};
x8.prototype.getPlayerContextData=x8.prototype.ha;
x8.prototype.na=function(a){var b=new i8(a);b.videoId&&b.videoId!=this.fb.videoId&&(this.B=b.videoId,g.bE(this.J),this.J=g.$D((0,g.A)(this.VV,this),5E3));var c=[];this.fb.listId==b.listId&&this.fb.videoId==b.videoId&&this.fb.index==b.index||c.push("remoteQueueChange");this.fb.o==b.o&&this.fb.volume==b.volume&&this.fb.muted==b.muted&&m8(this.fb)==m8(b)&&g.Dg(this.fb.A)==g.Dg(b.A)||c.push("remotePlayerChange");this.fb.reset(a);(0,g.C)(c,function(a){this.V(a)},this)};
x8.prototype.setPlayerContextData=x8.prototype.na;x8.prototype.Z=function(){var a=this.o.F.id,b=g.Ka(this.A,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
x8.prototype.getOtherConnectedRemoteId=x8.prototype.Z;x8.prototype.H=function(){var a=this.o;return a.A.isActive()?a.A.A-(0,g.G)():window.NaN};
x8.prototype.getReconnectTimeout=x8.prototype.H;x8.prototype.aa=function(){return this.C||"UNSUPPORTED"};
x8.prototype.getAutoplayMode=x8.prototype.aa;x8.prototype.da=function(){return this.G||""};
x8.prototype.getAutoplayVideoId=x8.prototype.da;x8.prototype.va=function(){if(!(0,window.isNaN)(this.H())){var a=this.o.A;g.du(a.o);a.start()}};
x8.prototype.reconnect=x8.prototype.va;x8.prototype.ka=function(a,b){D8(this,a,b);KDa(this)};
x8.prototype.sendMessage=x8.prototype.ka;g.B(E8,E7);g.h=E8.prototype;g.h.se=function(a){return this.ld.$_gs(a)};
g.h.contains=function(a){return!!this.ld.$_c(a)};
g.h.get=function(a){return this.ld.$_g(a)};
g.h.start=function(){this.ld.$_st()};
g.h.add=function(a,b,c){this.ld.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.ld.$_r(a,b,c)};
g.h.Kq=function(a,b,c,d){this.ld.$_un(a,b,c,d)};
g.h.X=function(){for(var a=0,b=this.A.length;a<b;++a)this.ld.$_ubk(this.A[a]);this.A.length=0;this.ld=null;E8.ea.X.call(this)};
g.h.sX=function(){this.V("screenChange")};
g.h.qT=function(){this.V("onlineScreenChange")};
N7.prototype.$_st=N7.prototype.start;N7.prototype.$_gspc=N7.prototype.tX;N7.prototype.$_gsppc=N7.prototype.bG;N7.prototype.$_c=N7.prototype.contains;N7.prototype.$_g=N7.prototype.get;N7.prototype.$_a=N7.prototype.add;N7.prototype.$_un=N7.prototype.Kq;N7.prototype.$_r=N7.prototype.remove;N7.prototype.$_gs=N7.prototype.se;N7.prototype.$_gos=N7.prototype.aG;N7.prototype.$_s=N7.prototype.subscribe;N7.prototype.$_ubk=N7.prototype.Yd;var F8=null,G8=null,V8=null,K8=[];g.t(W8,g.M);g.h=W8.prototype;
g.h.X=function(){g.M.prototype.X.call(this);this.C.stop();this.D.stop();this.L.stop();this.O();this.o.unsubscribe("proxyStateChange",this.CD,this);this.o.unsubscribe("remotePlayerChange",this.Jm,this);this.o.unsubscribe("remoteQueueChange",this.Pp,this);this.o.unsubscribe("autoplayUpNext",this.aD,this);this.o.unsubscribe("previousNextChange",this.zD,this);this.o.unsubscribe("nowAutoplaying",this.rD,this);this.o.unsubscribe("autoplayDismissed",this.ZC,this);this.o=this.H=null};
g.h.aC=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.o.o)if(Z8(this)){if(!r8(this.o).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":r8(this.o).rb()?this.o.pause():this.o.play();break;case "control_play":this.o.play();break;case "control_pause":this.o.pause();break;case "control_seek":this.K.Sj(c[0],c[1]);break;case "control_subtitles_set_track":$8(this,c[0]);break;case "control_set_audio_track":c=c[0],Z8(this)&&this.o.Iw(this.A.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.A.getCurrentTime();a9(this,0==c?void 0:c);break;case "control_seek":a9(this,c[0]);break;case "control_subtitles_set_track":$8(this,c[0]);break;case "control_set_audio_track":c=c[0],Z8(this)&&this.o.Iw(this.A.getVideoData(1).videoId,c)}};
g.h.nR=function(a){this.L.mK(a)};
g.h.TW=function(a){this.aC("control_subtitles_set_track",g.Zb(a)?null:a)};
g.h.oF=function(){var a=this.A.Ac("captions","track");g.Zb(a)||$8(this,a)};
g.h.pD=function(a){if(Z8(this)){this.o.unsubscribe("remotePlayerChange",this.Jm,this);var b=Math.round(a.volume);a=!!a.muted;var c=r8(this.o);if(b!=c.volume||a!=c.muted)this.o.setVolume(b,a),this.M.start();this.o.subscribe("remotePlayerChange",this.Jm,this)}};
g.h.IS=function(){g.Zb(this.F)||eEa(this,this.F);this.G=!1};
g.h.CD=function(a,b){this.D.stop();2==b&&this.kF()};
g.h.Jm=function(){if(Z8(this)){this.C.stop();var a=r8(this.o);switch(a.o){case 1081:case 1:Y8(this,new g.yP(8));this.jF();break;case 1085:case 3:Y8(this,new g.yP(9));break;case 1083:case 0:Y8(this,new g.yP(2));this.K.stop();X8(this,this.A.getVideoData().lengthSeconds);break;case 1084:Y8(this,new g.yP(4));break;case 2:Y8(this,new g.yP(4));X8(this,m8(a));break;case -1:Y8(this,new g.yP(64));break;case -1E3:Y8(this,new g.yP(128,{errorCode:"mdx.remoteerror",message:"\u0412\u0438\u0434\u0435\u043e \u043d\u0435\u0434\u043e\u0441\u0442\u0443\u043f\u043d\u043e \u0434\u043b\u044f \u0443\u0434\u0430\u043b\u0435\u043d\u043d\u043e\u0433\u043e \u0432\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0434\u0435\u043d\u0438\u044f."}))}a=
r8(this.o).A;var b=this.F;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.F=a,eEa(this,a));a=r8(this.o);-1==a.volume||Math.round(this.A.getVolume())==a.volume&&this.A.isMuted()==a.muted||this.M.isActive()||this.KF()}else dEa(this)};
g.h.zD=function(){this.A.V("mdxpreviousnextchange")};
g.h.Pp=function(){Z8(this)||dEa(this)};
g.h.yJ=function(){this.o.Zy()};
g.h.aD=function(a){a&&(a=g.qE("/watch_queue_ajax",{method:"GET",fd:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.A)(this.VU,this)}))&&(this.O=(0,g.A)(a.abort,a))};
g.h.VU=function(a,b){var c=new g.rO({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.A.V("mdxautoplayupnext",c)};
g.h.rD=function(a){(0,window.isNaN)(a)||this.A.V("mdxnowautoplaying",a)};
g.h.ZC=function(){this.A.V("mdxautoplaycanceled")};
g.h.lP=function(a,b){-1==r8(this.o).o?a9(this,a):b&&this.o.YF(a)};
g.h.KF=function(){if(Z8(this)){var a=r8(this.o);this.B.Ha(this.T);a.muted?this.A.mute():this.A.lg();this.A.setVolume(a.volume);this.T=this.B.R(this.A,"onVolumeChange",this.pD)}};
g.h.jF=function(){this.C.stop();if(!this.o.ma()){var a=r8(this.o);a.rb()&&Y8(this,new g.yP(8));X8(this,m8(a));this.C.start()}};
g.h.kF=function(){this.D.stop();this.C.stop();var a=this.o.C.getReconnectTimeout();2==this.o.o&&!(0,window.isNaN)(a)&&this.D.start()};g.t(b9,g.W);b9.prototype.D=function(a){gEa(this,a.state)};g.t(c9,g.zZ);c9.prototype.L=function(){var a=this.A.Ac("remote","receivers");a&&1<a.length&&!this.A.Ac("remote","quickCast")?(this.J=g.lb(a,this.F,this),g.AZ(this,(0,g.I)(a,this.F)),a=this.A.Ac("remote","currentReceiver"),this.Cf(this.F(a)),this.enable(!0)):this.enable(!1)};
c9.prototype.F=function(a){return a.key};
c9.prototype.Bf=function(a){return"cast-selector-receiver"==a?"\u0414\u043e\u0431\u0430\u0432\u0438\u0442\u044c":this.J[a].name};
c9.prototype.zd=function(a){g.zZ.prototype.zd.call(this,a);this.A.Td("remote","currentReceiver",this.J[a]);this.D.Tb()};g.t(d9,g.WU);g.h=d9.prototype;g.h.create=function(){YDa(g.OM(g.Y(this.o)));this.F.push(g.XF("yt-remote-before-disconnect",this.jR,this));this.F.push(g.XF("yt-remote-connection-change",this.bU,this));this.F.push(g.XF("yt-remote-receiver-availability-change",this.AD,this));this.F.push(g.XF("yt-remote-auto-connect",this.ZT,this));this.F.push(g.XF("yt-remote-receiver-resumed",this.XT,this));this.AD()};
g.h.load=function(){this.o.Gu();g.WU.prototype.load.call(this);this.D=new W8(this,this.o,this.A);var a=(a=cEa())?a.currentTime:0;var b=U8()?new q8(P8(),void 0):null;0==a&&b&&(a=m8(r8(b)));0!=a&&(this.J=a||0,this.o.V("progresssync",a,void 0));fEa(this,this.G,this.G);g.X_(this.o.app,6)};
g.h.unload=function(){this.o.V("mdxautoplaycanceled");this.C=this.B;g.df(this.D,this.A);this.A=this.D=null;g.WU.prototype.unload.call(this);g.X_(this.o.app,5)};
g.h.X=function(){g.YF(this.F);g.WU.prototype.X.call(this)};
g.h.zm=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.D.aC.apply(this.D,[a].concat(g.oa(c)))};
g.h.iK=function(){return this.loaded?this.D.suggestion:null};
g.h.dg=function(){return this.A?r8(this.A).dg:!1};
g.h.hasNext=function(){return this.A?r8(this.A).hasNext:!1};
g.h.getCurrentTime=function(){return this.J};
g.h.ZO=function(){var a=r8(this.A),b=this.o.getVideoData();return{allowSeeking:this.o.md(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.F?a.C+k8(a):a.C,isPeggedToLive:1>=(a.F?a.B+k8(a):a.B)-this.getCurrentTime(),loaded:a.K,seekableEnd:a.F?a.B+k8(a):a.B,seekableStart:0<a.D?a.D+k8(a):a.D}};
g.h.aP=function(){this.A&&this.A.WF()};
g.h.bP=function(){this.A&&this.A.XF()};
g.h.jR=function(a){1==a&&(this.K=this.A?r8(this.A):null)};
g.h.bU=function(){var a=U8()?new q8(P8(),void 0):null;if(a){var b=this.C;this.loaded&&this.unload();this.A=a;this.K=null;b.key!=this.B.key&&(this.C=b,this.load())}else g.cf(this.A),this.A=null,this.loaded&&(this.unload(),(a=this.K)&&a.videoId==this.o.getVideoData().videoId&&this.o.EB(a.videoId,m8(a)));this.o.V("videodatachange","newdata",this.o.getVideoData(),3)};
g.h.AD=function(){this.H=[this.B].concat($Da());var a=Q8()||this.B;e9(this,a);this.o.xa("onMdxReceiversChange")};
g.h.ZT=function(){var a=Q8();e9(this,a)};
g.h.XT=function(){this.C=Q8()};
g.h.YO=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.H;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?g8():e9(this,b)),this.loaded?this.C:this.B;case "quickCast":return 2==this.H.length&&"cast-selector-receiver"==this.H[1].key?(b&&g8(),!0):!1}};
g.h.cP=function(){v8(this.A,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Dc=function(){return!1};g.NX.remote=d9;})(_yt_player);
